### ISSUE TITLE
laravelのweb表示のさいの不具合

### ISSUE THREAD

**Issue by kuni1124** [rui1031/ecsaito#5]
https://gyazo.com/e6c8f50f6ceba5f82aff195726ee7570
画面の様にumekikunihiko@umekikunihikonoMacBook-Pro ecsaito % php artisan serve
Could not open input file: artisan　となっていしまいます。　
一度cd ecsaito　コマンドで移動という形をとると見れる様になるのですが、cd で移動させるのが今後開発に影響があるのか心配になってしまいまして。このまま開発を進めても大丈夫なのでしょうか？？

**Comment by okadakk** [comment]
```
$ mv ecsite/* .
$ rm -rf ecsite
```

でどうですかね？

**Comment by okadakk** [comment]
@rui1031 それか難しかったら、一度そのままでコミットしてもらえれば、綺麗にしときますよ
